#ifndef OBJECTS_H
#define OBJECTS_H
#include "game.h"
#include "tags.h"
#include "helpers.h"
#include "behaviours.h"
#include "actions.h"
#include "sprites.h"
#include "fx.h"
#include "sounds.h"

GameObject Corpse();
GameObject Player();
GameObject Spell();
GameObject BleedSpell();
GameObject LightningSpell();
GameObject Skeleton();
GameObject SkeletonLord();
GameObject Villager();
GameObject Bandit();
GameObject TheKing();
GameObject Champion();
GameObject ShellKnight();
GameObject Monk();
GameObject Archer();
GameObject Piper();
GameObject Rat();
GameObject RageKnight();
GameObject RoyalGuard();
GameObject RoyalGuardOrb();
GameObject Wizard();
GameObject Portal();
#endif // OBJECTS_H
